### ISSUE TITLE
Can't complete config flow

### ISSUE THREAD

**Issue by taw123** [a2hill/ha-thermoworks-cloud#1]
First thanks you and congrats regarding the integration!

I installed the HA integration via HACS but am unable to log into my ThermoWorks cloud account. Double checked and verified credentials and it is clear that feeding an INCORRECT password results in a different error msg (invalid_auth), whereas using my CORRECT credentials results only in the return code (unknown).

Do I also need to install the perl lib mentioned in your readme?  Assumed that your HA integration carried the full package. Might look while waiting to see if I can get any more data by trying to drive the API directly or perhaps see is I can enable debug in HA to get more data. Yeah I was an Engineer ;)

Thanks again for the help and efforts!    

-----

Update: here is the log of my previous attempts to complete the initial setup/config flow

```
This error originated from a custom integration.

Logger: custom_components.thermoworks_cloud.config_flow
Source: custom_components/thermoworks_cloud/config_flow.py:74 
integration: ThermoWorks Cloud (documentation, issues) 
First occurred: 11:07:23 AM (5 occurrences) 
Last logged: 11:26:17 AM

Unexpected exception: 'emailStatus'
Traceback (most recent call last):
  File "/config/custom_components/thermoworks_cloud/config_flow.py", line 74, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/thermoworks_cloud/config_flow.py", line 42, in validate_input
    await thermoworks_cloud.get_user()
  File "/usr/local/lib/python3.13/site-packages/thermoworks_cloud/core.py", line 46, in get_user
    return document_to_user(user_document)
  File "/usr/local/lib/python3.13/site-packages/thermoworks_cloud/models/user.py", line 107, in document_to_user
    email_status=fields["emailStatus"]["stringValue"],
                 ~~~~~~^^^^^^^^^^^^^^^
KeyError: 'emailStatus'
```

**Comment by taw123** [comment]
Sounds good. 

I’m hoping they aren’t actively trying to prevent access. Seem like good folks just aren’t focused on providing an open API so we can add features we are looking for so before I’m willing to buy any more products ( also considering quite a large RDX purchase to augment my Signals device and probes) when I know I will be able to either intercept the probe data (aka ESP-32 based 433 MHz project) or your approach grabbing data from cloud. 

Honestly they should allow cloud API access because if we can get the local data that would mean less interest in any cloud subscription services. So they ought to be good to us right 😉 lol

**Comment by a2hill** [comment]
Yeah its a shame to have to go through the effort of getting it from the cloud when its all sitting right there, but such is life. I also hope they aren't trying to prevent access. I did notice that they started requiring different referred headers shortly after I started working on this, but I think it was just a coincidence. 

The type issue I references earlier may also be a coincidence as well. I notice that when the temperature value coming from the device is a round number the type is `integerValue` and when it is a decimal value it changes to a `doubleValue`. 

Anyway, I've pushed a change that removes the failing value. Seems like emailStatus isn't a value that is present for all users as I still see it returned for my account, but it appears it wasn't being returned for yours. I can't actually test the change since its specific to the state of the account, do you mind giving it a try?

https://github.com/a2hill/python-thermoworks-cloud/commit/5e83cea9b122b6413abaf400d6cc8884f90005f4

**Comment by taw123** [comment]
Apologies for the delay, was buried here.

I'm confused...

I installed the HA Components via the DEFAULT HACS repo. Retested today with account and verified same response code unknown. (HACS reports as version: 367a09b). Manifest file states: 0.1.0 with requirement of therrmoworks_cloud == 0.1.7

The 2 files you posted above appear to be for your support library. I took a look through the 
```
[~] # ls -la "/share/DockerAppData/HomeAssistant/config/custom_components/thermoworks_cloud/"
total 107
drwxrwx---  3 admin         administrators        13 2025-03-16 11:47 ./
drwxrwx--- 69 HomeAssistant HomeAssistantGroup    72 2025-03-15 18:46 ../
-rwxrwx---  1 admin         administrators      4411 2025-03-11 22:14 config_flow.py*
-rwxrwx---  1 admin         administrators       230 2025-03-11 22:14 const.py*
-rwxrwx---  1 admin         administrators      5340 2025-03-11 22:14 coordinator.py*
-rwxrwx---  1 admin         administrators      6148 2025-03-16 11:58 .DS_Store*
-rwxrwx---  1 admin         administrators       101 2025-03-11 22:14 .gitignore*
-rwxrwx---  1 admin         administrators      3630 2025-03-11 22:14 __init__.py*
-rwxrwx---  1 admin         administrators       528 2025-03-11 22:14 manifest.json*
drwxrwx---  2 admin         administrators         6 2025-03-16 11:31 __pycache__/
-rwxrwx---  1 admin         administrators       150 2025-03-11 22:14 quality_scale.yml*
-rwxrwx---  1 admin         administrators     12615 2025-03-11 22:14 sensor.py*
-rwxrwx---  1 admin         administrators       910 2025-03-11 22:14 strings.json*
```

```
[~] # more "/share/DockerAppData/HomeAssistant/config/custom_components/thermoworks_cloud/manifest.json" 
{
  "domain": "thermoworks_cloud",
  "name": "ThermoWorks Cloud",
  "codeowners": [
    "@a2hill"
  ],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/a2hill/ha-thermoworks-cloud",
  "homekit": {},
  "iot_class": "cloud_polling",
  "issue_tracker": "https://github.com/a2hill/ha-thermoworks-cloud/issues",
  "loggers": [
    "thermoworks_cloud"
  ],
  "requirements": [
    "thermoworks_cloud==0.1.7"
  ],
  "single_config_entry": false,
  "ssdp": [],
  "version": "0.1.0",
  "zeroconf": []
}

```

I did NOT DIRECTLY install the perl support lib or repo project https://github.com/a2hill/python-thermoworks-cloud  Assume you install it automatically SOMEWHERE when HACS installs the ha-thermoworks-cloud INTERGRATION. 

So 2 questions. First on your initial request for re-test. Pulled the 2 files in the build link you sent. but not sure if I need too install for if by your comments you rolled these already into what's in HACS. Related to this, as I mentioned I ONLY installed the integration. Should I ALSO have installed the library from the second repo (tI doubt this but trying to check all possibilities)

Finally do I need to move to YOUR repo DIRECTLY (remove the HACS default integration and potentially add YOUR PERSONAL/DEV  repo too I can install/maintain from a more current integration ) to get what you want me to test moving forward? Or are all your changes making it upstream to the official HACS Repo?

Thanks. Still trying too get the hang of some things here in HA and HACS despite years using.

**Comment by a2hill** [comment]
Sorry for the confusion

> I did NOT DIRECTLY install the perl support lib or repo project https://github.com/a2hill/python-thermoworks-cloud Assume you install it automatically SOMEWHERE when HACS installs the ha-thermoworks-cloud INTERGRATION.

Yes that is correct, this isn't a dependency that you directly install, it will be installed automatically for you when you install  the integration. 

> So 2 questions. First on your initial request for re-test. Pulled the 2 files in the build link you sent. but not sure if I need too install for if by your comments you rolled these already into what's in HACS. Related to this, as I mentioned I ONLY installed the integration. Should I ALSO have installed the library from the second repo (tI doubt this but trying to check all possibilities)

Nope, all you need to do is install (or in this case update) the integration using the HACS UI in Home Assistant. It looks like you've already done this and are now getting a different error:

```
Unexpected exception: 'system'
Traceback (most recent call last):
  File "/config/custom_components/thermoworks_cloud/config_flow.py", line 74, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/thermoworks_cloud/config_flow.py", line 42, in validate_input
    await thermoworks_cloud.get_user()
  File "/usr/local/lib/python3.13/site-packages/thermoworks_cloud/core.py", line 46, in get_user
    return document_to_user(user_document)
  File "/usr/local/lib/python3.13/site-packages/thermoworks_cloud/models/user.py", line 120, in document_to_user
    for k, v in fields["system"]["mapValue"]["fields"].items()
                ~~~~~~^^^^^^^^^^
KeyError: 'system'
```

This is a new error, let me take a look at it

**Comment by a2hill** [comment]
Pushed what I think should be a fix, let me know how it goes

**Comment by taw123** [comment]
I tried you most recent push: bfffe0b

No dice, "unknown" response code. Log below. Will try what you suggested above (get token and feed manually), after posting this. Thanks again for your persistence. We'll get through this.....

```
This error originated from a custom integration.

Logger: custom_components.thermoworks_cloud.config_flow
Source: custom_components/thermoworks_cloud/config_flow.py:74 
integration: ThermoWorks Cloud (documentation, issues) 
First occurred: 2:53:04 PM (1 occurrences) 
Last logged: 2:53:04 PM

Unexpected exception: 'notificationSettings'
Traceback (most recent call last):
  File "/config/custom_components/thermoworks_cloud/config_flow.py", line 74, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/thermoworks_cloud/config_flow.py", line 42, in validate_input
    await thermoworks_cloud.get_user()
  File "/usr/local/lib/python3.13/site-packages/thermoworks_cloud/core.py", line 46, in get_user
    return document_to_user(user_document)
  File "/usr/local/lib/python3.13/site-packages/thermoworks_cloud/models/user.py", line 125, in document_to_user
    for k, v in fields["notificationSettings"]["mapValue"]["fields"].items()
                ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'notificationSettings'

```

**Comment by taw123** [comment]
Do you want to see hold off on your earlier suggestion so we have a test case for any revisions you want to make to the integration or move forward whit your earlier request?

**Comment by a2hill** [comment]
I think doing both is good. Ultimately I'd like to get the raw server response for your account, but I can also just preemptively make things optional which should remove the error

**Comment by taw123** [comment]
Wish I had better news....

Picked up a 4+ inch Steak to try to celebrate what I hoped would be a success but.... 

Updated and still failing setup

This error originated from a custom integration.

Logger: custom_components.thermoworks_cloud.config_flow
Source: custom_components/thermoworks_cloud/config_flow.py:74 
integration: ThermoWorks Cloud (documentation, issues) 
First occurred: 6:11:14 PM (1 occurrences) 
Last logged: 6:11:14 PM

Unexpected exception: 'deviceOrder'
Traceback (most recent call last):
  File "/config/custom_components/thermoworks_cloud/config_flow.py", line 74, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/thermoworks_cloud/config_flow.py", line 42, in validate_input
    await thermoworks_cloud.get_user()
  File "/usr/local/lib/python3.13/site-packages/thermoworks_cloud/core.py", line 46, in get_user
    return document_to_user(user_document)
  File "/usr/local/lib/python3.13/site-packages/thermoworks_cloud/models/user.py", line 131, in document_to_user
    device_order=parse_device_order(fields["deviceOrder"]["mapValue"]),
                                    ~~~~~~^^^^^^^^^^^^^^^
KeyError: 'deviceOrder'


At least I will eat well tonight :) 

Gonna fires up the grill and then look at the info you originally sent and see if it makes sense to me and decide if see if per chance you want me try it or let you keep wack-a-moleing this issue. 

Ideally I should wait and just help you get the setup flow to work so that no one else has to go through this issue if/when they find the integration.

BTW (unrelated issue). Where is the ACTUAL ThermoWorrks perl lib installed (per your other repo). Curioous for future as I tool a quick look at your API doc and might be cases where I might want to call it from outside the HA Integration (perhaps a script or such just thinking ahead)

Thanks for the help, and if you have something you want me to try in the next hour or so I should have a case I can actually test non the grill!

--T

**Comment by lordmuffin** [comment]
I am seeing the same issue with an error related to device order.  Is this an issue with thermoworks making continued code changes? Or it seems like users have different fields depending on registered devices?

**Comment by a2hill** [comment]
Yeah it seems like users have different fields depending on their registered devices (also potentially whether or not they have setup the mobile app in addition to the web app).

Right now I have a sample size of 1 so it’s tough for me to say. I’ve got some instructions here for getting the server response shape for your particular account, if you feel like doing that it would help me out

https://github.com/a2hill/ha-thermoworks-cloud/issues/1#issuecomment-2727637092

**Comment by taw123** [comment]
Ok

I’ll try look at your previous instructions tonight and see if I can get you some more data to act on in the next day or so. 

Thanks!



Tom Weyer 
Global Product Management
(415) 823-7672 |  ***@***.***

**Comment by lordmuffin** [comment]
Okay, so I am noticing that I am missing the deviceOrder section altogether.  This must be because I have the RFX Gateway and probes.  I am wondering where else they might have shoved this data in firebase..

Server response for reference:

{
  "name": "projects/thermoworks-cloud-production/databases/(default)/documents/users/QsTXqDZkTlh01ShqWHnLJXMRfvQ2",
  "fields": {
    "locale": {
      "stringValue": "en-US"
    },
    "use24Time": {
      "booleanValue": false
    },
    "provider": {
      "stringValue": "firebase"
    },
    "photoURL": {
      "stringValue": ""
    },
    "uid": {
      "stringValue": "REDACTED"
    },
    "roles": {
      "mapValue": {
        "fields": {
          "DataReader": {
            "booleanValue": true
          }
        }
      }
    },
    "timeZone": {
      "stringValue": "America/Chicago"
    },
    "lastLogin": {
      "timestampValue": "2025-04-05T18:46:59.299Z"
    },
    "displayName": {
      "stringValue": ""
    },
    "email": {
      "stringValue": "REDACTED"
    },
    "appVersion": {
      "stringValue": "1.75.8"
    },
    "accountId": {
      "stringValue": "REDACTED"
    },
    "preferredUnits": {
      "stringValue": "F"
    },
    "fcmTokens": {
      "mapValue": {
        "fields": {
          "REDACTED": {
            "booleanValue": true
          },
          "null": {
            "booleanValue": true
          }
        }
      }
    },
    "accountRoles": {
      "mapValue": {
        "fields": {
          "accountAdmin": {
            "booleanValue": true
          }
        }
      }
    }
  },
  "createTime": "2025-04-04T19:27:04.356624Z",
  "updateTime": "2025-04-05T18:46:57.721004Z"
}

**Comment by a2hill** [comment]
Interesting, I think you’re right. Are you able to log into cloud.thermoworks.com and inspect the network responses there?

**Comment by lordmuffin** [comment]
I did a network capture and I dont know exactly what to make of it.. I have har file, would that be of use to you?

**Comment by a2hill** [comment]
Yep that would be great, you can email it to ***@***.***

**Comment by lordmuffin** [comment]
Ugh thanks GitHub... How about you DM me on Discord? lordmuffinx69

**Comment by a2hill** [comment]
Didn't realize GitHub did that, just edited, try that

**Comment by davidbarratt** [comment]
I'm having the same problem, let me know if there is any information I can provide that would be helpful.

**Comment by a2hill** [comment]
@wyckoffbc It looks like you are seeing the same issue as @lordmuffin, the devices aren't listed in your user document like they are for my Node thermometer. If you want to record a request capture like I describe above (see comment directly above this one) I can take a look through that

**Comment by a2hill** [comment]
@cliffkujala This is helpful, thanks! Looks like you do have some devices listed, so I would expect that you should be able to see at least some of your devices when you setup the Home Assistant integration. What happens when you try to run this integration in home assistant?

**Comment by cliffkujala** [comment]
<img width="828" alt="Image" src="https://github.com/user-attachments/assets/72492b10-14b9-4e67-b8b7-886275fa7e2d" />

The integration page gives a: `Failed setup, will retry: Error communicating with API: 'color` warning.

I don't see any errors in my HA Core logs though, even with Debug Logging turned on.

**Comment by cliffkujala** [comment]
@a2hill if you need results from any other command line calls, or info from my browser console to help just let me know.

**Comment by cliffkujala** [comment]
@a2hill I don't think my `API: 'color' ` issue is here on the HA Integration, rather I think it is a problem with your python library, because I see similar errors if I run the examples/get_devices_for_user.py directly.

**Comment by cliffkujala** [comment]
@a2hill awesome.  

Like I said if you have any straight .py tests you want me to run, I also have the python library running in a simple debian based container, so we can test to see which sensors exist for the popular Signals and RFX devices.  Thermadata WiFi is probably less popular now that Node has launched for fridge/freezer monitoring.

**Comment by cliffkujala** [comment]
Commented on the linked commit.

**Comment by a2hill** [comment]
This latest commit should fix the issue of being unable to complete the configuration flow: https://github.com/a2hill/ha-thermoworks-cloud/commit/1ff6843cecd74ba53e759de204394a64ece176d5
Is anyone able to test? If you are already using HACS:
1. Navigate to the HACS tab in HA 
1. Click the 3 dots on the right side of the row containing this integration
1. Click re-download
1. In the settings tab of HA you will see a new notification for a repair of this integration, click on that and restart HA

**Comment by wyckoffbc** [comment]
> This latest commit should fix the issue of being unable to complete the configuration flow: [1ff6843](https://github.com/a2hill/ha-thermoworks-cloud/commit/1ff6843cecd74ba53e759de204394a64ece176d5) Is anyone able to test? If you are already using HACS:
> 
> 1. Navigate to the HACS tab in HA
> 2. Click the 3 dots on the right side of the row containing this integration
> 3. Click re-download
> 4. In the settings tab of HA you will see a new notification for a repair of this integration, click on that and restart HA

That worked to get the integration added to HA, but unfortunately I still don't have any devices listed 😢 
I re-ran those curl commands to see what is coming back, and there is still nothing in there that seems to list my devices, however when I go to the Thermoworks Cloud webpage, I definitely have these guys:

![Image](https://github.com/user-attachments/assets/23834ef9-d794-4299-ae14-0bc31540a09a)

**Comment by cdninnyc** [comment]
Chiming in here, just tried getting this setup myself. HA says I have 1ff6843. user/pass seems to be ok, no error there, but it's not pulling my Node as an entity. I only have the one Node setup in Thermo Cloud right now.

**Comment by cdninnyc** [comment]
I enabled debug logging after you suggested it above, and I also re-downloaded and restarted HA

**Comment by wyckoffbc** [comment]
I enabled debug logging, reloaded, disabled logging and got the brief log file attached here.  I redacted a few things, but I'm not sure if there is much useful information here.  I'm semi-smart, but not enough when it comes to this stuff, so if there is something else you'd like me to try I'm willing to give it a go, you'll just have to provide some clear steps like I'm a toddler...

[home-assistant_thermoworks_cloud_2025-06-10T20-41-12.891Z.log](https://github.com/user-attachments/files/20679804/home-assistant_thermoworks_cloud_2025-06-10T20-41-12.891Z.log)

**Comment by a2hill** [comment]
@wyckoffbc @cdninnyc I've got a new version out which I hope should fix the issue for everyone. Would appreciate it if you could try it out
https://github.com/a2hill/ha-thermoworks-cloud/issues/3#issuecomment-2965046401

**Comment by cdninnyc** [comment]
Fixed for my single Node, thank you very much. I have other Nodes and RFX on another account that I will migrate over and see if they pull in.

**Comment by a2hill** [comment]
@cliffkujala Lets track that here: https://github.com/a2hill/ha-thermoworks-cloud/issues/9
